### ISSUE TITLE
There might be a SQL inject issus in \admin\deleteCategorie.php

### ISSUE THREAD

**Issue by FStac** [Paroxyste/Simply-Blog#1]
issus start at line 7 to line 10
`if(isset($_POST["submit"])) {
  $DeleteFromURL = $_GET["delete"];
  $Query = "DELETE FROM category WHERE id='$DeleteFromURL'";
  $Execute = mysqli_query($Connection, $Query);
`
We can see intuitively that database queries are not filtered，so attacker can inject payload into Query directly
SUGGEST:
i think you can add character filtering to check user input before execute the query

**Comment by Paroxyste** [comment]
Hello and thank you for bringing the problem to my attention.

Can you tell me if the problem is now solved? Sorry, I'm a beginner.

**Comment by FStac** [comment]
i think you can set a syntax to check user input string dose contain special chars like (' , + '' or -) ,if it does,then split it out or give a error response directly.

**Comment by Paroxyste** [comment]
Thanks for your advice, I blocked the special characters of the inputs. If you have any other ideas, don't hesitate to tell me about them.

Please block your script, you're saturating my mailbox.
Sincerely.
